### ISSUE TITLE
new size categories for physical entities (BODCNVS-1136)

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/S29#1]
New S19s required:
63-160um
160-250um
163-250um
10000-13000um
13000-16000um
400-1250um
2000-2500um
2500-3150um
3150-4000um
2500-4000um
4000-5000um
5000-6300um
6300-8000um
8000-10000um
12500-16000um
16000-20000um
6300-10000um
25-63um
1600-4000um
12500-25000um
1000-1600um
63-163um
50-200um
2-10um
10-63um
10000-16000um
2000-31500um
31500-4000um
40-63um
63-200um
50000-200000um
6300-20000um
>125000um

To associate with the S18 for particles

**Comment by roswri** [comment]
S19s created:
S1901334	63-160um
S1901335	160-250um
S1901336	163-250um
S1901337	10000-13000um
S1901338	13000-16000um
S1901339	400-1250um
S1901340	2000-2500um
S1901341	2500-3150um
S1901342	3150-4000um
S1901343	2500-4000um
S1901344	4000-5000um
S1901345	5000-6300um
S1901346	6300-8000um
S1901347	8000-10000um
S1901348	12500-16000um
S1901349	16000-20000um
S1901350	6300-10000um
S1901351	>125000um
S1901352	25-63um
S1901353	1600-4000um
S1901354	12500-25000um
S1901355	1000-1600um
S1901356	63-163um
S1901357	50-200um
S1901358	2-10um
S1901359	10-63um
S1901360	10000-16000um
S1901361	2000-31500um
S1901362	31500-4000um
S1901363	40-63um
S1901364	63-200um
S1901365	50000-200000um
S1901366	6300-20000um


4000-5000um and 50-200um were duplicated in supplied list

**Comment by roswri** [comment]
S29s created:
PE001455	particles (12500-16000um)
PE001472	particles (50000-200000um)
PE001471	particles (63-200um)
PE001470	particles (40-63um)
PE001469	particles (31500-4000um)
PE001468	particles (2000-31500um)
PE001467	particles (10000-16000um)
PE001466	particles (10-63um)
PE001473	particles (6300-20000um)
PE001456	particles (16000-20000um)
PE001457	particles (6300-10000um)
PE001458	particles (>125000um)
PE001444	particles (10000-13000um)
PE001445	particles (13000-16000um)
PE001446	particles (400-1250um)
PE001447	particles (2000-2500um)
PE001448	particles (2500-3150um)
PE001449	particles (3150-4000um)
PE001450	particles (2500-4000um)
PE001451	particles (4000-5000um)
PE001452	particles (5000-6300um)
PE001453	particles (6300-8000um)
PE001454	particles (8000-10000um)
PE001459	particles (25-63um)
PE001460	particles (1600-4000um)
PE001461	particles (12500-25000um)
PE001462	particles (1000-1600um)
PE001463	particles (63-163um)
PE001464	particles (50-200um)
PE001465	particles (2-10um)
PE001443	particles (163-250um)
PE001442	particles (160-250um)
PE001441	particles (63-160um)

**Comment by roswri** [comment]
Possible typo:
31500-4000um
should it be 31500-40000um or 3150-4000um? The latter is already in the list

**Comment by gwemon** [comment]
@roswri  I checked the source and it should be 31500-40000um

**Comment by roswri** [comment]
31500-4000um updated to 31500-40000um in S19/S29.
Closing ticket.
