### ISSUE TITLE
NTR: sampling station

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S29#18]
Relates to https://github.com/nvs-vocabs/P01/issues/229

Proposed definition: A location at which measurements or samples were taken.

**Comment by dr-shorthair** [comment]
'location or facility' - there is often some fixed infrastructure involved.

**Comment by ahpanton** [comment]
New S18 created:
S1800132 sampling station - A location or facility at which measurements or samples were taken

New S29 created:
PE001546 sampling station - definition as above

**Comment by ahpanton** [comment]
S29: 
[sampling station](http://vocab.nerc.ac.uk/collection/S29/current/PE001546/)- A location or facility at which measurements or samples were taken
