### ISSUE TITLE
NTR: sampling processor (upper filter)  and sampling processor (lower filter)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S29#26]
2 new combined S29 terms needed for: https://github.com/nvs-vocabs/P01/issues/227

 "sampling processor (upper filter) " with definition "The top filter in a cascade or sequential filtration setup designed to exclude material retained by the filter. Only material and liquid that pass through the filter are used in the analyses."

and

"sampling processor (lower filter) " with definition "The bottom filter in a cascade or sequential filtration setup used to collect particulate material from a sample (typically water sample). Only the material collected on the filter is used in the analysis."

**Comment by jakjonbodc** [comment]
sampling processor (lower filter) - http://vocab.nerc.ac.uk/collection/S29/current/PE001522/
sampling processor (upper filter) - http://vocab.nerc.ac.uk/collection/S29/current/PE001519/
