### ISSUE TITLE
NTR: spatial replicate

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S29#27]
Related to: https://github.com/nvs-vocabs/P01/issues/207

Proposed definition: samples collected independently over some area, specifically collected to estimate statistical information about that area.

**Comment by ahpanton** [comment]
New S18 required:
S1800129 spatial replicate, description as above

S29 created using new S18, S1900001 (not applicable), S2000001 (not applicable)

PE001523 spatial replicate, description as above

**Comment by ahpanton** [comment]
http://vocab.nerc.ac.uk/collection/S29/current/PE001523/
