### ISSUE TITLE
NTR: temporal replicate

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S29#28]
Related to: https://github.com/nvs-vocabs/P01/issues/207

Proposed definition: samples collected independently over a timeframe, specifically collected to estimate changes to the subject of interest over that timeframe.

**Comment by ahpanton** [comment]
New S18 required:
S1800128 temporal replicate, description as above

S29 created using this S18, S1900001 (not applicable), S2000001 (not applicable)

PE001524 temporal replicate, description as above

**Comment by ahpanton** [comment]
http://vocab.nerc.ac.uk/collection/S29/current/PE001524/
