### ISSUE TITLE
NTR: technical replicate

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S29#29]
related to: https://github.com/nvs-vocabs/P01/issues/207

Proposed definition: Subsamples, or repeated processing, of a parent sample, to capture variation in handling of each replicate, or simply to repeat the processing.

**Comment by ahpanton** [comment]
New S18 required:
S1800127 technical replicate, description as above

New S29 created using new S18, S1900001 (not applicable), S2000001 (not applicable)

PE001525 technical replicate, description as above

**Comment by ahpanton** [comment]
http://vocab.nerc.ac.uk/collection/S29/current/PE001525/
