### ISSUE TITLE
NTR: biological replicate

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S29#30]
related to: https://github.com/nvs-vocabs/P01/issues/207

Proposed definition: Biologically distinct samples that are collected in parallel to capture random biological variation.

**Comment by ahpanton** [comment]
New S18 created:
S1800126 Biological replicate, description as above

S29 created using this S18 , S1900001 (not applicable) and S2000001 (not applicable)

PE001526, biological replicate, description as above

**Comment by ahpanton** [comment]
http://vocab.nerc.ac.uk/collection/S29/current/PE001526/
