### ISSUE TITLE
NTR: new combination needed for platform and device orientation

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S29#31]
We need the following 3 new S29 combinations to complete https://github.com/nvs-vocabs/P01/issues/257:

measurement platform relative to magnetic north (S18+S20)
measurement device (S18) --> new S18 needed
measurement device relative to True North (S18+S20)

**Comment by SLBlakeman** [comment]
New terms available on the NVS 8th May 2024:

New S18: S1800130 "measurement device" 
New S29:
[PE001542](https://vocab.nerc.ac.uk/collection/S29/current/PE001542)	measurement platform relative to magnetic north
[PE001543](https://vocab.nerc.ac.uk/collection/S29/current/PE001543)	measurement device
[PE001544](https://vocab.nerc.ac.uk/collection/S29/current/PE001544)	measurement device relative to True North
