### ISSUE TITLE
NTR: new S29 to describe heat

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/S29#5]
New S29 to be created for heat.

**Preferred label:** heat
**Definition:** Energy transferred to or from a thermodynamic system, by means of convection, conduction, radiation or friction.

This is in relation to https://github.com/nvs-vocabs/P01/issues/157

**Comment by danibodc** [comment]
This term has been loaded and will be live on the NVS from tomorrow morning.

**Comment by gwemon** [comment]
https://vocab.nerc.ac.uk/collection/S29/current/PE001487/
